README.md
It was still pointing to the DART-2.0 testing repository, it should now go to the DART issues page.
=> Fix the link to the issue page

assimilation_code/programs/obs_seq_to_netcdf/obs_seq_to_netcdf.f90
The namelist option 'append_to_netcdf' was not implemented properly when there were multiple output files. If there was only 1 file, it has always worked correctly. If 'append_to_netcdf = .false.' the output files are always overwritten, no matter how many of them there are.
=> Addressing Issue #12 appending incorrectly

observations/obs_converters/GOES/convert_goes_ABI_L1b.f90, observations/obs_converters/GOES/goes_ABI_L1b_mod.f90, observations/obs_converters/GOES/work/input.nml
It's sometimes helpful, even though definitely wrong from a theoretical standpoint, to give a vertical location to satellite observations (which are integrated quantities). This has been an issue with observation-space localization for some time, and this is the standard workaround pioneered by Lili Lei and Jeff Whittaker.
=> Can now specify vloc in pressure for GOES obs converter

assimilation_code/modules/utilities/random_seq_mod.f90, assimilation_code/modules/utilities/time_manager_mod.f90
the fortran standard says defining a binary, octal or hexadecimal constant
is not allowed without using one of the numeric intrinsics like int(val, kind)
or real(val, kind) to specify the kind explicitly.  gcc10 now flags this as
an error, which is new.  fix the two places where 'z' constants were being used.
=> fix z'0123' without an explicit int() or real() intrinsic

assimilation_code/modules/utilities/random_seq_mod.f90, assimilation_code/modules/utilities/time_manager_mod.f90
This addresses the gnu 10 compiler discovery that
we were not following the standard for declaring
hexadecimal constants.
=> Adding the content from public PR 56

assimilation_code/modules/assimilation/filter_mod.f90
When doing posterior state-space inflation, to update inflation, filter_assim is called a second time with inflate_only = .true.  This step is unnecessary if using RTPS inflation, as there's nothing to update when using RTPS.
=> One-line fix to bypass posterior inflation update if RTPS option

models/POP/shell_scripts/cesm2_1/CESM2_1_setup_hybrid, models/POP/shell_scripts/cesm2_1/CESM2_1_setup_pmo, models/POP/shell_scripts/cesm2_1/user_datm.streams.txt.CPLHISTForcing.Solar_template, models/POP/shell_scripts/cesm2_1/user_datm.streams.txt.CPLHISTForcing.State1hr_template, models/POP/shell_scripts/cesm2_1/user_datm.streams.txt.CPLHISTForcing.State3hr_template, models/POP/shell_scripts/cesm2_1/user_datm.streams.txt.CPLHISTForcing.nonSolarFlux_template
Since the coupler history files for the CAM Reanalysis are now
unzipped on RDA, we edit the POP user_datm.streams* templates and the
CESM2_1 setup scripts for running PMO and setting up a hybrid ensemble
to enable them to make use of the unzipped files.
This fixes Github NCAR/DART Issue #87.
The changes were tested by building a hybrid case using CESM2_1_setup_hybrid
and ensuring that the case ran to completion. Results here:
/glade/work/johnsonb/cases/GNYF.f09_g17_e40.001/ GNYF.f09_g17_e40.001.run.o5254429
CESM2_1_setup_pmo was not run because the changes to it are identical to
those made for CESM2_1_setup_hybrid and the latter script is effectively, in this
case, a superset of the former.
=> Update POP user_datm.streams & scripts for cesm2_1

models/mpas_atm/model_mod.f90, observations/forward_operators/obs_def_rttov_mod.f90
Aim of this pull request is to commit the work Nancy and Soyoung did on MPAS and RTTOV. 
Fixes https://github.com/NCAR/DART_development/issues/119
The rttov obs_def changes:
* E_ALLMSG used instead of E_MSG
* loc_sea variable used to create `sfc`, `2m`, `10m` locations relative to model surface elevation
* monotonically decreasing pressure from TOA check now has greater than or **equal to**  ( this is the bug fix)
The mpas_atm model_mod changes:
* Debugging info in the comment at the start of the module. 
* New error code for pressure not monotonically decreasing with level
* QTY_CLOUD_FRACTION added.  Force non-negative hydrometeors and for QTY_CLOUD_FRACTION <1
* `compute_scalar_with_barycentric` passing `tavs(1)`, `values(1,:)`. when `n=1`.  There is some discussion of this in …
=> mpas rttov 

models/wrf/tutorial/README.md
Thanks to Ilya Livshits for reporting the error.
=> Referencing correct location of input.nml.template

assimilation_code/modules/assimilation/adaptive_inflate_mod.f90, assimilation_code/modules/assimilation/filter_mod.dopplerfold.f90, assimilation_code/modules/assimilation/filter_mod.f90
From Moha:
Improved the support for RTPS (inf_flavor 4) posterior inflation: 
Previously, one could only decide on a single parameter (say, alpha) in the input nml (as inf_initial(2)) without being able to see what is the effective posterior inflation the RTPS scheme is actually using. In other words, if you check the resulting inflation in preassim.nc for instance (variable state_postinf_mean) it would be the same as inf_initial(2). That's incorrect. 
To clarify, there is nothing wrong in the RTPS implementation, however, reporting the output has an issue. The following update corrects the issue and updates the output files with the right posterior inflation values. See the figure below for illustration. The left hand side plot is the value of state_postinf_mean in preassim.nc (or …
=> Improved the support for RTPS (inf_flavor 4) posterior inflation: 

observations/forward_operators/obs_def_radar_mod.f90
In observations/forward_operators/obs_def_radar_mod.f90, if reflectivity (QTY_RADAR_REFLECTIVITY) is in the state, right now, the subroutine get_expected_radar_ref immediately "return"s.  However, by returning, the subroutine never gets to apply the "apply_ref_limit_to_fwd_op" check, which is problematic.
This simple fix actually allows the "apply_ref_limit_to_fwd_op" check to happen if reflectivity is in the state.
=> Bug fix to allow reflectivity forward operator limit check.

assimilation_code/modules/assimilation/quality_control_mod.f90
Currently, to disable the outlier check, we set outlier_threshold < 0 in the namelist.
However, doing so effectively eliminates logic related to **enable_special_outlier_code**; if outlier_threshold < 0, quality_control_mod.f90 never gets to the part where it checks if enable_special_outlier_code is enabled.
This is problematic for someone who might want to disable the outlier check for all obs types _except for _some__.  I came across this issue when I was using precomputed forward operators for all observation types except for radar obs, and I wanted to keep DART's outlier check for radar obs but wanted to eliminate the check for everything else.
Suggested fix restores functionality of enable_special_outlier_code when outlier_threshold < 0
=> Modify logic for outlier_threshold < 0

assimilation_code/modules/observations/obs_sequence_mod.f90, assimilation_code/programs/obs_sequence_tool/obs_sequence_tool.f90, observations/forward_operators/DEFAULT_obs_def_mod.F90
The obs_sequence_tool was not writing out FO values when working with obs_seq.out files that contain FO values. I modified the obs_sequence_tool code along with DEFAULT_obs_sequence_mod.F90 to read the namelist option that users select to have FO values outputted.
=> write FO values with obs_sequence_tool

observations/forward_operators/DEFAULT_obs_def_mod.F90
Fixes https://github.com/NCAR/DART/issues/173
Each task has every copy of the precomputed FO because the whole ensemble is in `obs_def%external_F0`
Each task calculates the forward operator for the copies it has.
For distributed_state = true this is the whole ensemble
For distributed_state = false this is a subset of the ensemble.
This fix adds a loop in `get_expected_obs_from_def_distrib_state` to grab the correct subset of copies from `obs_def%external_F0.`
=> bug fix for external forward operators when using distributed_state=.false.

assimilation_code/programs/obs_utils/obs_info.f90, observations/utilities/oned/input.nml, observations/utilities/threed_sphere/input.nml
the original program may have worked on obs kinds which do start
at 0, but these are now handling obs types which start at 1.
make all arrays and loops start at index 1.  also fix the input.nml
namelists for obs_info_nml to have better defaults.
this is related to [issue #147](https://github.com/NCAR/DART/issues/147)
(low priority.  just figuring out the simpler workflow with git.)
=> obs_info fix

CHANGELOG.rst
The documentation has also been changed to build off the main branch.
People visiting the NCAR/DART GitHub site get instructions on how to change their local repositories to accomodate this change.
=> Making 'main' (aka 'master') the default branch.

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md, CHANGELOG.rst, README.md, README.rst, conf.py, guide/downloading-dart.rst
Removed the instructions for checking out the 9.10.0 tag.  Main is now the default branch so people will get the latest version of DART by default when they clone the repository. 
Pull request template - with checklist for updating changelog and tag when merging
Issue templates - bug fix and feature requests. 
You can view what the templates look like here: https://github.com/hkershaw-brown/DART/issues/new/choose
Fixes issue https://github.com/NCAR/DART/issues/212
draft of release email (editable) https://docs.google.com/document/d/1XCbM-9SduixHTmA8vuc8lB-MlHbQarv5g96YVQcnotk/edit?usp=sharing
=> changes for release email

observations/obs_converters/obs_error/README.rst, observations/obs_converters/utilities/create_sphere_obs.f90, observations/obs_converters/utilities/threed_sphere/input.nml, observations/obs_converters/utilities/threed_sphere/path_names_create_sphere_obs
updates to create_sphere_obs to make it more general:
- additional items have been added to the namelist so they can
be changed at runtime rather than at compile time.
- the errors for radiosonde obs are now taken from the ncep (or ecmwf)
error module.
- a bug in the pressure values has been fixed. the original version kept
them in hectopascals instead of converting to pascals.
- additional comments have been added about the matlab version..
- minor wordsmithing in the obs_error README for clarity.
- NOT DONE, but should be:
after kevin's pull request is accepted i would like to move this
file into the even_sphere directory.  it isn't a utility and having
it along with the build files in the same directory as the matlab
means it will be easier to find.  the readme will need updating so
i …
=> make create_sphere_obs more general

assimilation_code/programs/obs_utils/obs_info.f90, assimilation_code/programs/obs_utils/obs_info.nml, observations/utilities/oned/input.nml, observations/utilities/threed_sphere/input.nml
made a separate array to store the info for identity obs
rather than try to support negative indices in the oinfo array.
also fix time string formatting if running with no calendar.
=> obs_info should handle identity obs without crashing

assimilation_code/location/threed_sphere/location_mod.f90, assimilation_code/modules/assimilation/filter_mod.f90, assimilation_code/modules/assimilation/sampling_error_correction_mod.f90, assimilation_code/modules/io/direct_netcdf_mod.f90, assimilation_code/modules/io/io_filenames_mod.f90, assimilation_code/modules/io/state_structure_mod.f90, assimilation_code/modules/io/state_vector_io_mod.f90
First wave of changes to support CLM on main branch. Changes primarily revolve around the separate handling of `_FillValue` and `missing_value` attributes and takes pains to ensure that they are identical if both present. 
Relates to #224 - but does not fix it entirely.
I ran the test_dart.csh suite on Cheyenne with the environment below and nothing broke. Additionally, I ran tests on the bgrid model, changing various attributes to trigger the various code blocks.
```
Currently Loaded Modules:
1) ncarenv/1.3           4) mpt/2.22       7) nco/4.9.5      10) hdf-eos5/5.1.16
2) intel/19.0.5          5) netcdf/4.7.4   8) ncview/2.1.7
3) ncarcompilers/0.5.0   6) mkl/2019.0.5   9) diffuse/0.4.8
```
Rather than test what I tested, I'd like you to test what you think needs testing. We might test …
=> CLM update 1

CHANGELOG.rst, conf.py, models/cam-fv/model_mod.f90
Fix cam-fv model_mod to pass correct quad_vals to quad_lon_lat_evaluate. 
fixes issue #246
Tested with cam-fv on Cheyenne 8 member ensemble
/glade/scratch/hkershaw/DART/Bugs/bug_246/cam_fv/[test_fix test_main]
*Note*:
quad_utils_mod.f90 uses ` invals(4, nitems)`
cam-fv/model_mod.f90 uses  `quad_vals(ens_size,4) !< array of interpolated values`
which seems ripe for bugs such as #246.   I'm not sure why the change in order was made, maybe should be reverted.
=> bugfix for issue #246 quad_vals

CHANGELOG.rst, conf.py, models/wrf/model_mod.f90
Fixes issue #258
Initialize uniqiek in wrf model_mod to have an invalid level
Fixes #258 
Bitwise with main branch (caveat the 288 processor case which showed the bug). 
Cheyenne, intel & gnu compilers.
Test case here: 
/glade/work/hkershaw/DART/cheyenne_run288
=> bug-fix: initialize uniquek to an invalid level.

observations/obs_converters/NCEP/prep_bufr/convert_bufr/grabbufr.f, observations/obs_converters/NCEP/prep_bufr/convert_bufr/stat_test.f
Added a declaration for the STAT function to grabbufr.f and stat_test.f
Without the declaration, when using the PGI compiler you get the following error for long(ish) filenames 
e.g.  prepqm20012912.no_ship_id
ERROR IN FUNCTION STAT GETTING FILE INFO, RC =   -2147483648
#256
Compared grabbufr on 8 buffer files.  The files are here:
/glade/scratch/hkershaw/DART/Bugs/bug_256/test_many
PGI, intel, gfortran.  Results are identical to using grabbufr built with `install.sh` from the main branch.  However see note in issue #256 on the main branch -O changes the results.  I think this is a bug not a feature. 
stat_test used to check long filenames.
=> bug-fix: add declaration for STAT function

assimilation_code/programs/obs_seq_to_netcdf/obs_seq_to_netcdf.f90, assimilation_code/programs/obs_seq_to_netcdf/radiance_obs/obs_seq_to_netcdf.f90
Added logic to obs_seq_to_netcdf to keep track of whether a files has been created for an epoch during that run of obs_seq_to_netcdf.  Previously if there were multiple obs_sequence files in an epoch, the epoch file was being created afresh for each obs_seq file. Thus, only obs from the last file in the list were present in obs_epoch.nc 
#12 
Epochs set for 1 day long for the month of February:
```
&schedule_nml
calendar             = 'Gregorian'
first_bin_start      =  2012,  2,  1,  0,  0,  0
first_bin_end        =  2012,  2,  2,  0,  0,  0
last_bin_end         =  2012,  3,  1,  0,  0,  0
bin_interval_days    = 1 
bin_interval_seconds = 0 
max_num_bins         = 31  
print_table          = .true.
/   
```
List of obs_sequence …
=> bug-fix: Obs_seq_to_netcdf appending files 

CHANGELOG.rst, assimilation_code/modules/io/direct_netcdf_mod.f90, assimilation_code/modules/io/state_structure_mod.f90, assimilation_code/modules/io/state_vector_io_mod.f90, assimilation_code/modules/utilities/ensemble_manager_mod.f90, assimilation_code/modules/utilities/mpi_utilities_mod.f90, assimilation_code/programs/perfect_model_obs/perfect_model_obs.f90, conf.py, developer_tests/mpi_utilities/tests/Makefile, developer_tests/mpi_utilities/tests/ftest_sendrecv_big.f90, developer_tests/mpi_utilities/tests/input.nml, models/template/readme.rst, models/utilities/default_model_mod.rst, models/wrf/model_mod.f90
Model size in DART can be an i8 number. However, some of the indexing into the state vector was not set up to use i8.
This problem was discovered by a user was running a large wrf perfect_model_obs (3796738754 elements in the state vector).
This pull request contains:
* wrf model_mod.f90 fixes to use i8  for model size. This includes removing the function `get_wrf_index` which is not used (and not i8)
* direct_netcdf_mod.f90, state_structure_mod.f90, state_vector_io_mod.f90 have i8 integers for variables that deal with indices into the state vector. 
* mpi_utitliites_mod.f90  `itemcount` is now i8 so the `else` clause of `if (itemcount <= SNDRCV_MAXSIZE)` is entered.  Bug fix 
in the receive section for number of elements sent (was itemsize, now next size)
There is a test added in …
=> Model size i8 fix for state vector io and mpi_utilities

CHANGELOG.rst, assimilation_code/modules/assimilation/filter_mod.dopplerfold.f90, assimilation_code/modules/assimilation/filter_mod.f90, conf.py
The nvidia compiler enforces the fortran standard that characters in namelists must have "" or ''. This pull request removes the 
"string or integer namelist" option added in pull request https://github.com/NCAR/DART/pull/154. It does not remove any of the integer parameters added to to adaptive_inflate_mod in  https://github.com/NCAR/DART/pull/154
The standard is:
Note 10.33, in 10.9.1.3
"A character sequence corresponding to a namelist input item of character data type shall be delimited either with apostrophes or quotes. The delimiter is required to avoid ambiguity between undelimited character sequences and object names. The value of the DELIM = specifier, if any, in the OPEN statement for an external file is ignored during namelist input "
(Note 10.36 in the f2008 standard).
Fixes …
=> bug-fix character namelist values need to be the same type as variable

CHANGELOG.rst, assimilation_code/modules/assimilation/adaptive_inflate_mod.f90, conf.py
Bug fix for rpts with inflate=1
Follows the non-rtps order of operations to avoid inflation of 1.0 changing ens.
Please provide a summary of the change and include any relevant motivation and context. 
Fixes #353 
```
$cat test_order.f90 
program order
implicit none
integer,parameter :: n = 3
real*8 :: ens(n), mean, inflate
real*8 :: ens2(n), ens3(n), ens4(n)
integer :: i
inflate = 1.d0
do i = 1, n
ens(i) = real(i,8)/10000
mean = mean + ens(i)
enddo
!mean = mean/real(n,8)
! This is not the mean, just a number to trigger differences in the 
! calculation for this test code
mean = 4.0d8
ens2 = mean + (ens-mean) * inflate 
ens3 = ens * inflate + mean * (1.d0 - inflate)
ens4 = ens*inflate + mean - mean*inflate
print*, 'mean', mean
print*, 'ens ', ens
print*, 'ens2 ', ens2
print*, 'ens3 ', …
```
=> bug-fix: rtps inflation 

CHANGELOG.rst, conf.py, models/MITgcm_ocean/model_mod.f90
* Querying the variable id and clamping value for each state element.  
In pert_model_copies the state vector is spread out round-robin across the processors, so the check for clamping value must be done for each element.  
* INDICES loop is now `INDICES : do i = 1, state_ens_handle%my_num_vars`.  Previously the INDICES loop was 
`INDICES : do i = start_ind, end_ind` which caused pert_model_copies to segfault.
* Removed module global random_seq since this is not used.
fixes #360 
Perturbed MIT ocean test case.
Here is a test case for filter log_transform=.false.
/glade/scratch/hkershaw/DART/MITgcm/test_small_domain.no-nans.no-log
And for log_transform=.true.
/glade/scratch/hkershaw/DART/MITgcm/test_small_domain.no-nans.log
=> Fix for  MITgcm_ocean pert_model_copies

CHANGELOG.rst, assimilation_code/modules/assimilation/assim_tools_mod.f90, conf.py
Removal of redundant caching in the get_close_obs_cached and get_close_state_cached subroutines in DART/assimilation_code/modules/assimilation/assim_tools_mod.f90 . 
- Make close_X arrays intent(inout)
- Remove the explicit caching and copying in `last_close_X_dist = close_X_dist` and `last_close_X_ind = close_X_ind` 
- Remove all other instances of the last_close_X_dist and last_close_X_ind arrays
Fixes #364 
(optimization)
Tested with WRF, cam-fv, and MPAS_ATM. Test cases can be found in /glade/scratch/hkershaw/DART/siparcs2022/test_cases
The outputs of ensemble runs implementing the revised code proved to be bitwise identical with WRF and cam-fv runs on the main branch. 
WRF and cam-fv were also built with all debugging flags, which did not produce any relevant errors or warnings. 
The …
=> Redundant caching in assim_tools_mod.f90

models/mpas_atm/model_mod.f90
There may be multiple variables with the same qty in the state.
`get_varid_from_kind` errors out if there is more than one variable
of that quantity.
This fix uses `get_num_varids_from_kind` instead
fixes #386
run mpas with these two QTY_POTENTIAL_TEMPERATURE variables in the state.
```
&mpas_vars_nml
mpas_state_variables =  'theta',  'QTY_POTENTIAL_TEMPERATURE',
'th2m',   'QTY_POTENTIAL_TEMPERATURE'
...
```
/glade/scratch/hkershaw/DART/MPAS/test_run
=> bug-fix: mpas_atm call get_num_varids_from_kind to check if a qty is in the state

.gitignore, CHANGELOG.rst, build_templates/buildfunctions.sh, conf.py, models/wrf_hydro/work/quickbuild.sh
obs_utitiles_mod is only for threed_sphere and threed_cartesian location_mods. 
It should not be included in all model builds.
Remove obs_utilites_mod from model buildfunctions.sh and add to wrf_hydro quickbuild.sh
fixes #383
Note this pull request does not make obs_utilities_mod work with all location_mods, just stops  obs_utitlies_mod being compiled into the model programs by default.
build_everything
=> bug-fix: remove obs_utilites_mod from model buildfunctions.sh

CHANGELOG.rst, conf.py, models/POP/shell_scripts/cesm2_1/DART_params.csh
On Cheyenne, the POP assimilate script doesn't propagate the inflation files properly due to the fact that the link command isn't configured to force the reassignment of a symbolic link if the destination is already present. This fix adds the `-f` option when `$LINK` is defined within the scripts to force reassignment of the symbolic link.
#392
None.
Created a test case on Cheyenne to verify that this fixes the problem.
```
cd /glade/work/johnsonb/git/DART_fix_POP/models/POP/shell_scripts/cesm2_1
./setup_CESM_hybrid_ensemble.csh
cd /glade/work/johnsonb/cases/GNYF.f09_g17_e3test
./case.submit -M begin,end
[ ... Case runs to completion without data assimilation ]
./CESM_DART_config.csh
[ ... Configure case to enable data assimilation ]
./xmlchange CONTINUE_RUN=TRUE
./xmlchange STOP_N=1 …
```
=> Add -f option to ln command for POP scripts

models/mpas_atm/model_mod.f90
Removed unnecessary array initializations from get_close_state() and get_close_obs() subroutines in the MPAS_ATM model_mod.f90
`close_ind = -99 `
`if (present(dist)) dist = 1.0e9_r8   !something big and positive (far away) in radians`
Their removal causes a significant reduction to the runtime (can be more than 20%) when running MPAS_ATM cases with large model_size.
See issue for more info.
Fixes issue #405 
Tested to be bitwise identical with both Intel and GNU Fortran.
MPAS_ATM was also built and run with all debugging flags, which did not produce any relevant errors or warnings.
For an execution of a high-memory case on Casper (96 ensemble members, 459,985 observations, model_size = 327,759,048), the runtime was reduced from 145 min. to 112 min. or about %23
For an execution of …
=> Removal of unnecessary, expensive array initializations in the MPAS_ATM model_mod.f90

CHANGELOG.rst, conf.py, models/template/model_mod.f90
Fixes #409
This is a quick fix for the bug found by Molly Wieringa in the observation converter quickbuilds.
A models/template/model_mod.f90 is required
Does not address #408 ( developer test builds)
Template model_mod.f90
fixes #409 
Compile obs_converters and model_mods
=> model_mod.f90 in template directory

CHANGELOG.rst, assimilation_code/modules/io/direct_netcdf_mod.f90, conf.py
DART created netcdf files vs. model created files do not necessarily have the same netcdf dimensions. 
For DART created files only 'time' gets created as unlimited.  The model netcdf files, e.g. WRF, may have an unlimited dimension 'Time' that is converted limited dimension when DART creates a file from scratch. So if you create an inflation file from scratch with DART `fill_inflation_restart`, it may not match the model template file.
This pull request adds a check to see if the unlimited dimension exists and adjust accordingly before reading netcdf variables.
The bug was introduced in pull request https://github.com/NCAR/DART/pull/374 v10.1.0 for TIEGCM.
The write_variables has the check, but the read_variables was overlooked. 
See …
=> bug-fix: add a check for unlimited dimension in read_variables 

CHANGELOG.rst, assimilation_code/programs/perfect_model_obs/perfect_model_obs.f90, assimilation_code/programs/perfect_model_obs/perfect_model_obs.nml, assimilation_code/programs/perfect_model_obs/perfect_model_obs.rst, conf.py, models/POP/work/input.nml
Perfect_model_obs was giving incorrect obs_seq.out (forward operators) when the  model was advanced in perfect_model_obs **and** perfect_model_obs was run with multiple processors (using the default namelist option of `distributed_state = .true.`)
This pull request moves the mpi window creation and destruction for perfect_model_obs inside the AdvanceTime do loop. The forward operator needs to use state from each step of the loop, so the window must be recreated.
Why do we need to create a window each time? Because currently the mpi window is created using a copy of the state. 
Edit:
This pull request also removes the namelist option `distribute_state` from pmo.
The perfect_model_obs code is not setup to do non-distrbuted state foward operators - the obs loop is around my_num_vars. Compare …
=> move window creation and destruction for perfect_model_obs

models/clm/work/quickbuild.sh
The conversion from mkfmf_* quickbuld.csh to quickbuild.sh missed fill_inflation_restart for clm.
This pull request:
* adds fill_inflation_restart to the default list of programs for clm.
* removes perturb_single_instance since clm cannot be perturbed from a single ensemble member.
The quickbuild.sh list of programs now matches the v9.16.4 list.
No issue, user reported this weekend to dart email. The user was working through the The CLM-DART tutorial which uses fill_inflation_restart.
Built clm programs, checked the list of programs against v9.16.4 mkmf_*
=> fix: fill_inflation_restart (re)added to default builds for clm

CHANGELOG.rst, conf.py, models/cam-fv/shell_scripts/cesm2_1/assimilate.csh.template
This modification of the assimilate.csh.template for cam-fv fixes the issue in which restart files sometimes aren't being purged when the interval between restart saves is a string rather than an integer.
fixes #435  
Set up a FHIST run on the `f09_g17` grid and cycled for two weeks to ensure that this change fixes the issue.
=> Edit cam-fv assimilate.csh.template to improve purge logic for restarts

CHANGELOG.rst, conf.py, guide/matlab-observation-space.rst, theory/readme.rst
There's a broken link on the DART Tutorial page for Configuring Matlab® for netCDF & DART:
https://raw.githubusercontent.com/NCAR/DART/v10.6.0/theory/readme.rst
fixes #441  
I rebuilt the documentation using Sphinx to check that the two edited pages render correctly.
=> Fix broken link in DART tutorial

models/wrf/shell_scripts/gen_retro_icbc.csh
We have had a couple of users hit problems when running the wrf tutorial 
This pull request fixes one of the common issues, a second setting of paramfile which can be easily missed in
`gen_retro_icbc.csh` 
fixes the first problem in #295
Run `./gen_retro_icbc.csh` , check `source $paramfile` is using the paramfile I set.
=> wrf tutorial fix: remove unnecessary and misleading second 'set paramfile' in gen_retro_icbc.csh

CHANGELOG.rst, assimilation_code/modules/assimilation/filter_mod.f90, assimilation_code/modules/observations/forward_operator_mod.f90, assimilation_code/modules/utilities/cray_win_mod.f90, assimilation_code/modules/utilities/no_cray_win_mod.f90, assimilation_code/modules/utilities/null_win_mod.f90, conf.py, models/wrf/shell_scripts/gen_retro_icbc.csh
There are several bugs in the QC handling that cause the DART QC data to be overwritten or lost. Specifically, the value for DARTQC_FAILED_VERT_CONVERT (8) was not ending up in the obs_seq.final after forcing convert_vertical_obs to return a failing vstatus. 
This pull request:
- Fixes the QC data being overwritten in obs_fwd_op_ens_handle%copies in the transpose from vars to copies in free_state_window() at line 310 forward_operator_mod
- Removes a misplaced call to put_single_copy() that also overwrites the QC data in obs_fwd_op_ens_handle%copies
- Includes @nancycollins fix for the QC values being lost if posterior FOs are not being computed (compute_posterior=.false.) (see PR #430) 
Fixes the multiple bugs in issue #401 
Tested with cam-fv and wrf; runs of filter with the implemented …
=> Bugfix QC8

CHANGELOG.rst, assimilation_code/modules/assimilation/adaptive_inflate_mod.f90, assimilation_code/modules/assimilation/filter_mod.dopplerfold.f90, assimilation_code/modules/assimilation/filter_mod.f90, assimilation_code/modules/assimilation/smoother_mod.f90, conf.py, observations/obs_converters/NSIDC/HDF5_utilities_mod.f90
This pull request fixes 3 refactoring issues:
* removed `state_ens_handle` from the `adaptive_inflate_init` arguments. `state_ens_handle` is unused in `adapative_inflate_init`, and (more seriously) not initialized until _after_ the call to `adaptive_inflate_init`.
* filter_mod  - fixed an untrue comment
* hd5f_utilities_mod removes some HFD5 tutorial code that made its way into the repo and fixes an i4 i8 mismatch that prevents compilation with modern compilers. 
Fixes #340 #70 #68
compiling everything in DART
=> remove  state_ens_handle  from adaptive_inflate_init arguments

developer_tests/forward_operators/work/quickbuild.sh, developer_tests/io/work/quickbuild.sh, developer_tests/obs_sequence/work/quickbuild.sh, developer_tests/quad_interpolate/work/quickbuild.sh, developer_tests/random_seq/work/quickbuild.sh, developer_tests/time_manager/work/quickbuild.sh, developer_tests/utilities/work/quickbuild.sh
Fixes the developer_tests `quickbuild.sh`s. Explicit model_mod.f90 given for each test, since we now have a template for 1d and 3d models. 
Fixes bug described in #408 
fixes #408 
Please describe any tests you ran to verify your changes:
* compiled and ran the developer_tests.
Note you'll need to link to rttov for the forward_operator tests.
=> bug-fix: developer test quickbuilds

CHANGELOG.rst, conf.py
Add sphinx_rtd_theme so we use the latest version of the rtd theme.
This fixes the search function and flyout menu for readthedocs documentation
See issue #471 for discussion
fixes #471 
Built the docs, checked the search and the flyout menu (version choice bottom left) worked:
https://docs.dart.ucar.edu/en/doc-search-fix/README.html
compare to https://docs.dart.ucar.edu/en/v10.7.1/README.html
=> fix: add sphinx_rtd_theme to extensions in conf.py

models/mpas_atm/model_mod.f90
Removed the nonfunctioning latlon_to_xyz_on_plane() subroutine from DART/models/mpas_atm/model_mod.f90.
This also got rid of some compiler warnings when compiling mpas_atm on Derecho with cce.
Fixes #496 
Simply compiled mpas_atm to ensure there were no dependencies on the removed code.
=> Remove unused latlon_to_xyz_on_plane() subroutine from the mpas_atm model_mod

assimilation_code/modules/assimilation/filter_mod.f90
i was looking for something else and noticed a misleading comment in filter_mod
I compiled lorenz 96 and ran it.
=> fix misplaced comment about writing an obs_seq file

models/MOM6/model_mod.f90, observations/obs_converters/GTSPP/GTSPP.rst, observations/obs_converters/WOD/WOD.rst
Added notes/warning for the unit change by the observation converters. 
WOD, GTSPP
MOM6 convert salinity to MSU in model_interpolate
Fixes #509 
Documentation build.
=> fix: salinity units for observation converters WOD and GTSPP an MOM6

models/wrf/model_mod.f90
Previously observations with VERTISUNDEF were given a large distance, because the vertical coordinate is missing: local_array(3) == missing_r8
https://github.com/NCAR/DART/blob/1b76f3afa5978469d6a119710bb638c1c077ae20/models/wrf/model_mod.f90#L6423-L6424
The location_mod::get_dist uses horizontal distance only if VERTISUNDEF for either location.
Fixes #486 
Tested using an example case from Lukas K. 
#486 and https://github.com/NCAR/DART/compare/main...lukas-vertundef-wrf
Note lukas-vertundef-wrf has changes for wrf v4, this pull request only has the VERTISUNDEF bug fix.
=> bug-fix: get_dist calculation for observations with VERTISUNDEF in WRF

CHANGELOG.rst, conf.py, models/MOM6/model_mod.f90, models/MOM6/readme.rst
This pull request fixes read_model_time MOM6:
* MOM6 time is in days from year 1.  DART time is from 1601.  This pull request converts MOM6 time to DART time in read_model_time. 
* Documentation updated to show how to turn on leap years for CESM (the default is no leap year).  Added an example in the docs to illustrate Time in days vs. YYYY-MM-DD when you do not have leap years. 
* The write_model_time is **not** converted back to MOM6 time. See #494 for discussion on this.  DART created files have dart time to match the observation times. 
fixes #494 
=> Bug-fix: Mom6 time

models/mpas_atm/model_mod.f90, models/mpas_atm/readme.rst
mpas updated the constants in v5: https://github.com/MPAS-Dev/MPAS-Model/commit/d2b19b6237e98f33d20e62428dcdf044b5106f2a
This fix is consistent with latest version of MPAS: v8.0.1
updated model_mod constants:
* cp, cv, rvord
* theta_m and pressure use rvord (=1.608362) instead of 1.61
rho is dry air density - comments changed to reflect this. 
fixes #251 
=> mpas_atm model_mod constants updated to match version 5+ of MPAS

.readthedocs.yaml, CHANGELOG.rst, assimilation_code/modules/assimilation/filter_mod.rst, assimilation_code/programs/filter/filter.rst, conf.py, guide/downloading-dart.rst, index.rst, models/CESM/doc/setup_guidelines.rst, models/clm/tutorial/README.rst, models/mpas_atm/model_mod.f90, models/mpas_atm/readme.rst, models/wrf/tutorial/README.rst
* Added an explicit target for the welcome page (index.rst). The links to README.rst were relative using the filename, so had to be updated for the rename to index.rst. 
* Using root_doc instead of master_doc to follow latest sphinx conf.py guidance 
* explicit conf.py following readthedocs v2 configuration
fixes #526
Tested the build on readthedocs:
fix-doc-index branch build: https://readthedocs.org/projects/dart-documentation/builds/21507857/
=> readthedocs build fix

CHANGELOG.rst, conf.py, models/cam-fv/shell_scripts/cesm2_1/assimilate.csh.template, models/cam-fv/shell_scripts/cesm2_1/setup_advanced, models/cam-fv/shell_scripts/cesm2_1/setup_hybrid
Several small independent upgrades to cam-fv shell scripts, that have accumulated over the past months and should be committed before further work in my clone.  They address the definition of a temp directory, checking the existence of inflation files, and defining RUNDIR at the right place.
None
None
I ran the setup scripts and they set up cases correctly.
- [x ] Dataset needed for testing available upon request
"Dataset" = all of the files needed to set up a cam-fv assimilation; too many to list here.
=> Cam fv small fixes

observations/forward_operators/obs_def_rttov13_mod.f90
radiance_obs_seq_to_netcdf with rttov13 failed to compile with error #6580: Name in only-list does not exist or is not accessible [GET_CHANNEL]. Fix: Added public get_channel to obs_def_rttov13_mod.f90 to compile WRF successfully.
fixes #532 
Add radiance_obs_seq_to_netcdf to ./quickbuild.sh. Then, run ./quickbuild.sh radiance_obs_seq_to_netcdf on DART/wrf/work.
=> Added get_channel to obs_def_rttov13_mod.f90

observations/forward_operators/obs_def_rttov13_mod.f90
obs_def_rttov13_mod.f90 was failing to compile on Derecho using CCE because "Assignment of a INTEGER expression to a LOGICAL variable is not allowed"
This pull request removes cloud_overlap (integer) from the function: `get_rttov_option_logical`
Also includes pull #540 
Fixes #537, #532 
Compile with cce (Cray Fortran 15.0.01) on Derecho.
Edit:
/glade/derecho/scratch/hkershaw/DART/Bugs/issue_537/build_templates/mkmf.template for building with rttov13_cray on Derecho.
=> bug fix: remove cloud_overlap integer from list of logicals to query 

index.rst, models/lorenz_96_tracer_advection/readme.rst, observations/obs_converters/Ameriflux/level4_to_obs.rst
This pr fixes the documentation warnings in:
index.rst -> added new_model template and fluxnetfull_to_obs to toctree
models/lorenz_96_tracer_advection/readme.rst -> removed unnecessary indentation in line 66
observations/obs_converters/Ameriflux/level4_to_obs.rst -> uncapitalized "f" for fluxnetfull_to_obs.rst
This pr resolves the remaining documentation warnings in Issue #546.
fixes #546 
After these changes, I ran "make clean" then "make html" to verify that no warnings were left.
=> Fixes for remaining documentation warnings in #546

assimilation_code/modules/utilities/random_seq_mod.f90, developer_tests/random_seq/test_ran_unif.f90
This a couple of commits that were meant to go in pull #549 
See #549
https://github.com/NCAR/DART/pull/549#issuecomment-1741246989
Compile and run developer test
=> remove loop from Mersenne twister test

assimilation_code/modules/assimilation/filter_mod.dopplerfold.f90
filter_mod.dopplerfold.f90 out of sync with filter (missing the latest QC bug fix https://github.com/NCAR/DART/pull/450
fixes: #565
I don't believe there is documentation for filter_dopplerfold at the moment. It is a hidden feature.
Compiled wrf with filter_mod.dopplerfold.f90
```
cd DART/wrf/work
cp ../../../assimilation_code/modules/assimilation/filter_mod.dopplerfold.f90 filter_mod.f90
./quickbuild.sh 
```
=> fix: sync filter_mod.dopplerfold with filter_mod

.github/actions/build_run_model/action.yml, .github/workflows/action_on_pull_request.yml, CHANGELOG.rst, conf.py
Adds a new check to the Github Actions workflow that uses the mpif08 module (compiles with ./quickbuild mpif08 and runs filter on 2 mpi tasks with the lorenz_96 model). 
This allows for the automatic testing of the mpif08 module when triggered by a new pull request and/or updates to a pull request.
There are now three total checks in our Actions workflow (build-run-lorenz_96-mpi, build-run-lorenz_63-nompi, build-run-lorenz_96-mpif08)
fixes #563 
Tested on my fork of DART by using a mock pull request to run the three total checks. All pass successfully and use the correct modules/input options.
[https://github.com/mjs2369/DART/pull/1](https://github.com/mjs2369/DART/pull/1)
=> Github Actions mpif08 check

observations/obs_converters/AIRS/airs_obs_mod.f90, observations/obs_converters/AIRS/work/input.nml
the convert_airs_L2 converter was printing 1 more obs converted than was actually done.
also, the settings for the convert_airs_L2 namelist thinned out all the obs.  change the defaults to include all possible obs, including all latitudes, and give an example filename for input instead of a list name.  the input file isn't in our repo, but it might help a user see what kind of filename they're looking for.
fix printout of number of obs converted to be right.
also change namelist defaults to not thin out all obs 
fixes #596 
i built and ran this with my copy of the updated HDF_EOS libraries and it printed out the correct number of obs.  it also didn't thin them all out.
=> fix print of number of obs converted, and make input.nml defaults better

assimilation_code/modules/assimilation/bnrh_distribution_mod.f90
Removed an amplitude adjustment factor from inv_bnrh_cdf. This was a legacy bit of code
that was required to bitwise reproduce earlier versions. About half of ensemble sizes
continue to bitwise reproduce with this change using Jeff's lorenz96_tracer_mod tests.
For the others, the amp_adj was different from 1 at the smallest writeable decimal
point and the tests ran producing reasonable, but no longer backward compatible,
results. 
See description.
=> Eliminate amp adjustment

assimilation_code/modules/utilities/assert_mod.f90
Fix for format statement in assert_mod. The goal of putting in this seemingly inconsequential change in is so the NAG compiler can be used to build dart, and not error out on this. 
The other NAG build error is fixed in #588.
fixes nag compiler (item 2) #615
```
program test_assert
use assert_mod, only : assert_equal_logical_array
implicit none
logical :: a(3), b(3)
a(:) = .true.
b(:) = .false.
call assert_equal_logical_array(a,b, 'beans on toast')
end program test_assert
```
add test_assert to serial_programs in quickdbuild.sh 
```
./quickdbuild.sh test_assert
./test_assert 
```
=> fix: format statement in assert_mod

README.md, models/wrf/tutorial/README.rst
remove register for dart link because this no longer exists:
* README.md
* models/wrf/tutorial/README.rst
Added Apache license badge to README.md
Please provide a summary of the change and include any relevant motivation and context. 
Fixes #616 if you ignore the header in every file. 
Built docs with sphinx locally. 
Previewed README.md with macdown.
=> remove register for dart link because this no longer exists

assimilation_code/modules/assimilation/filter_mod.f90
The function count_state_ens_copies had inconsistent ordering of the arguments in the function's definition and calls. This PR corrects this problem.
fixes #613 
Tested to be bitwise identical with filter runs using the old ordering of the arguments (with both cam-fv and wrf)
=> bug-fix: out of order args in count_state_ens_copies function

models/template/model_mod.f90, models/template/oned_model_mod.f90, models/template/threed_model_mod.f90, models/template/work/threed_input.nml
The templates for 3d models did not have good defaults for single files/obs_diag
This had tripped up users adding new models. 
This pull request provides improved defaults, and removes some svn relics from the templates model_mods (register_model)
Moved the oned initialize routine contents to static_init_model.
fixes #493
created a oned and threed_sphere new model, checked that quickbuild.sh was successful for both
./new_model.sh a_1d_model oned
./new_model.sh a_3d_model threed_sphere
For the defaults, compared threed_sphere with wrf input.nml
=> Improve defaults for model templates input.nml

assimilation_code/modules/assimilation/filter_mod.f90, guide/qceff_probit.rst
If RTPS inflation is selected, the probit inflation qceff options are silently ignored for posterior inflation. 
This pull request adds a message from filter to notify the user, and adds a note in the qceff docs about RTPS.
fixes #748
Run lorenz_96_tracer with RTPS inflation (posterior inf_flavor = 4) to check the message is printed (and not printed for post inf_flavor /= 4)
=> Notify user if using RTPS inflation that QCEFF options ignored for posterior inflation

CHANGELOG.rst, assimilation_code/programs/obs_diag/oned/obs_diag.f90, conf.py
Modified oned/obs_diag.f90 to add an unused singleton level
dimension to the output netcdf fields. These files now work with all of the relevant observation space diagnostic matlab programs. This was tested for plot_rank_histogram.m, plot_evolution.m, and plot_rmse_xxx_evolution.m for lorenz_96, lorenz_63, lorenz_84, and lorenz_96_tracer_advection, the latter with multiple observation types.
Added a new level dimension, added extra dimensions to array that processes the input from the obs_seq file.
fixes https://github.com/NCAR/DART/issues/230
See summary.
=> Modified oned/obs_diag.f90 to add an unused singleton level

models/lorenz_63/work/input.workshop.nml, models/lorenz_96/work/input.workshop.nml
Added probit_transform_nml and algorithm_info_nml to the 
input.workshop.nmls that were missing these (lorenz_63 and lorenz_96)
so the workshop_setup.sh scripts run to completion.
Updated the preprocess_nml to use obs_type quantity files. 
fixes #789
Ran all the workshop_setup.sh scripts
=> fix lorenz_93 and lorenz_63 workshop input.nmls to have v11 version of namelist

CHANGELOG.rst, conf.py, models/MOM6/model_mod.f90
All temperature observations were failing the forward operator for MOM6 because model_interpolate was only doing interpolation if the QTY was in the state & QTY_TEMPERATURE is not part of the model state.
MOM6 has QTY_POTENTIAL_TEMPERATURE so this needs converting to QTY_TEMPERATURE 
Following the method in the POP model_mod. I haven't generalized the code across both model_mods 1) because the salinity units are different between the models 2) POP has depth of grid points static across the ensemble vs thickness in the state for MOM6, 3) I don't want to mess with the POP model_mod
pseudo code:
```
pressure = f(depth)
pot_temp = f(QTY_POTENTIAL_TEMPERATURE, QTY_SALINITY, pressure) 
```
**Need to double check the units on pressure (dbars vs bars) and salinity (MSU vs PSU)**
Note sure of the …
=> fix: potential temp to temp conversion for MOM6 model_interpolate

CHANGELOG.rst, conf.py, models/wrf/model_mod.f90
Mandate in WRF-DART that if THM variable is present in &model_nml it must be ' perturbed dry adiabatic potential temperature'.   This is set through USE_THETA_M option in WRF &dynamics namelist.
Fixes #837 
None required.
=> Check for THM USE_THETA_M attribute

assimilation_code/programs/obs_common_subset/obs_common_subset.rst, assimilation_code/programs/obs_selection/obs_selection.rst
partial fix for #808, the link to the  obs_selection program was missing. 
changed link for obs_sequence tool to use the anchor rather than a relative path
partial #808
=> doc-fix: link for obs_selection

assimilation_code/modules/assimilation/bnrh_distribution_mod.f90
Corrected the upper limit on loop to compute the CDF at each value in the x vector (subroutine bnrh_cdf_initialized_vector); this needs to be the size of the x vector (num) instead of the size of the ensemble. Also ensured that all the comments now correctly matched the code, which they did without needing any changes
Fixed typos in the names of the calling subroutines passed into check_bounds from the bnrh_distribution_mod (EX: inf_bnrh_cdf -> inv_bnrh_cdf)
Fixes issue #844 as well as undocumented typos in call to check_bounds
Tested bitwise identical using the [Example A (bounded normal rank histogram)](https://docs.dart.ucar.edu/en/latest/guide/qceff-examples.html#example-a:~:text=or%20Microsoft%20Excel.-,Example%20A,-%EF%83%81) of the QCEFF Examples with the Lorenz 96 Tracer Model
=> bug-fixes: small bugs in the bnrh_distribution_mod.f90

assimilation_code/programs/perturb_single_instance/perturb_single_instance.rst
Allows you to copy the example and paste it into your input.nml without throwing and error for missing namelist.
Also ens_size is an integer so should not be in quotes.
fixes #862
Built the docs.
=> fix doc namelist name for perturb_single_instance

CHANGELOG.rst, conf.py, models/tiegcm/model_mod.f90
Fixes problems in model_interpolate for VTEC 
- result of 4 corners was not being stored correctly, overwriting corner11
- domain of ZG was incorrect
- units of ZG for need to be m in the vtec calculation
I've taken out the todo "test vtec" 🙃 
fixes #851
None yet, just compiled user reported changes.  
Derecho is down today.
=> fix: vtec extrapolation calculation in TIEGCM

observations/obs_converters/radar/README.rst
The obs converter radar documentation was deprecated and pointed to an old google archive version (OPAWS) that converted DORADE and FORAY radar formats.   New documentation now points to pyOPAWS converter developed by NOAA and capable of converting more commonly used NEXRAD radar format.   pyOPAWS is a viable option for both WRF and MPAS radar DA applications.
Fixes issue #827 .  
- [ X] I have updated the documentation accordingly.
I have run the pyOPAWS test case within the example instructions using Derecho.  I have provided Quickstart instructions
within the new documentation that provides required steps for both generating diagnostic plots and radar obs_seq.out files.
Testing NEXRAD datasets already provided with the pyOPAWS package.
=> Updated radar observation docs

build_templates/mkmf.template.cce
Setting cce to follow ieee. fpn1 fixes #871, but setting fpn0 since we have had other compilers hit ieee problems (see #557).  See https://github.com/NCAR/DART/issues/871#issuecomment-2956602017 for ieee reproducer.
From cray compiler docs https://cpe.ext.hpe.com/docs/24.11/getting_started/CPE-CCE-Fortran.html 
 fpn[=[no]approx]
Controls the level of floating point optimizations, where n is a value between 0 and 4, with 0 giving the compiler minimum freedom to optimize floating point operations and 4  giving it maximum freedom. The higher the level, the less the floating point values conform to the IEEE standard. 
fixes #871 
Ran developer tests for normal distribution
=> set ieee for cce compiler in mkmf.tempate

CHANGELOG.rst, assimilation_code/modules/assimilation/assim_tools_mod.rst, assimilation_code/modules/utilities/ensemble_manager_mod.rst, conf.py, guide/data-management-issues.rst, guide/forward_operator.rst, guide/vertical-conversion.rst
I have added the specific namelist options for data management in dart, when the "whole" state vector is required
and what the namelist options do. 
I have added the specific namelist options for when vertical conversion is done, what the defaults are set to and why.
I removed some very out-of-date routines ({read|write}_ensemble_restart) from the ensemble manager documentation and removed references to the prepare_vars etc that was removed in #637.
fixes #879
fixes #882
fixes #881
Built the documentation locally, read it, clicked the links between pages.
=> Documentation for namelist options for data management and vertical conversion temporal choice

.github/actions/build_run_model/action.yml, .github/workflows/action_on_pull_request.yml
Github action on pull request new container with dartuser no need to run as root for mpi
No issue, note on openmpi with one process #917 but this is not used in the action
updated action
This pull request is a test
=> Use new container for github action-on-pull

assimilation_code/programs/perfect_model_obs/perfect_model_obs.f90
1) Adds a conditional to the print statements in pmo "Processing observation         X  of        Y" so that the error_handler is called with E_ALLMSG if pmo is being run on more than 1 mpi proc
This fixes the issue that was occurring where it was only printing the the obs on task 0, which made it appear that only those obs were being processed
2) Also adds a conditional to only call print_obs_time if on task 0, fixing the issue of it printing the same thing on every task
NOTE that now that we are not using trace_message, these prints will NO LONGER be executed if the namelist option silence is set to true
fixes #905 
fixes #922  
Ran pmo for lorenz models and MOM6 with various numbers of MPI procs and values for …
=> bug-fix: perfect_model_obs prints

CHANGELOG.rst, conf.py, models/MOM6/model_mod.f90, models/MOM6/readme.rst
Bug fixes for MOM6 
Fix: correct u grid for get_interp_handle
Fix: large dist set only for dry land state indices
simplifies the wet/dry for a single point. 
Fixes #930 
Fixes #929
Fixes #933
Fixes #934 
=> MOM6: correct u grid for get_interp_handle, correct distance when there are land points in get_close_state

CHANGELOG.rst, conf.py, guide/Radiance_support.rst, guide/contributors-guide.rst, guide/requesting-features-reporting-bugs.rst, index.rst
Improved contributors guide
* More friendly tone
* More concrete explanation of what you can do to contribute and how.
* remove quick-start for developers because it is out-dated, also not sure developers should be quick starting. 
* removed separate requesting-features-reporting-bugs.rst since this is covered in contributors guide.
fixes #813
Build documentation locally
=> Improved contributors guide

CHANGELOG.rst, conf.py, guide/available-observation-converters.rst, index.rst, observations/obs_converters/CrocoLake/convert_crocolake_obs.py, observations/obs_converters/CrocoLake/crocolake_to_obsseq_example1.py, observations/obs_converters/CrocoLake/crocolake_to_obsseq_example2.py, observations/obs_converters/CrocoLake/readme.rst, observations/obs_converters/README.rst
This is an observation converter for CrocoLake part of the CROCODILE project, contributed by Enrico Milanese, Woods Hole Oceanographic Institution (WHOI) 
This converter has been on the [CROCODILE-CESM/DART ](https://github.com/CROCODILE-CESM/DART) fork. It takes the parquet format data of CrocoLake and converts to observation sequence format. 
Note the commits are flattened into one commit here, because we have a bunch of MOM6 assimilate.sh for crocodile that are not ready for DART. If you want more detail see #603 original closed pull request or #920 for details on cesm-hybrid issue, but this pull request is only concerned with the CrocoLake converter. 
Fixes #884 
Run the converter on Derecho, ingest with obs_sequence_tool
=> feat: Crocolake observation converter
