NCAR/DART

- docs/pages/Publications.md
While converting the LMDZ README to reStructuredText, I found a publication to add to Publications.md.
> Update Publications.md with LMDZ publication

- observations/obs_converters/GSI2DART/README.rst
Also -- trying to unwrap long lines to facilitate side-by-side comparisons.
> giving Craig recognition, adding one issue

- docs/pages/Presentations.md
- docs/pages/Publications.md
- models/FESOM/README.md
Adding two publications and adding enough whitespace at the end of the lines to
force the title and journal to be on new lines.
> Twopubs agu2020

- assimilation_code/modules/utilities/options_mod.f90
Fixes: https://github.com/NCAR/DART/issues/104
The description is from the original commit of options_mod.f90
4ab9fd71fd85cad2b6fc6e786905ee2595b99047
> options_mod.f90 comment fix

- observations/forward_operators/DEFAULT_obs_def_mod.F90
No functional changes but added comments to explain what is going on and why.
Added a little whitespace because I had a hard time reading the code.
> documenting precomputed forward operator support.

- docs/_config.yml
Added jemoji plugin to be able to show emoji on github pages site. 
Fixes: https://github.com/NCAR/DART/issues/78
> Added emoji plugin to _config.yml

- docs/pages/Publications.md
> Add Karspeck et al. 2013 to Publications

- models/wrf_hydro/python/experiment/requirements.txt
fixed syntax issue with matlabengine, updated notebook dependency.
James has actually removed this file from his working directory, so there is no problem moving forward.
These changes are already on the master branch.
> resolved dependabot alert about notebook

- assimilation_code/modules/utilities/random_seq_mod.f90
fixes https://github.com/NCAR/DART/issues/152
reported by Chris Reidel
> correct comment in random_seq_mod

- assimilation_code/programs/filter/filter.html
Added a user-guide on how to use RTPS inflation. Also,
added few sentences to update already existing text with
recent research. Missing references have also been appended.
> Documenting RTPS inflation algorithm

- assimilation_code/programs/gen_sampling_err_table/gen_sampling_err_table.rst
- assimilation_code/programs/readme.rst
- assimilation_code/programs/system_simulation/system_simulation.rst
This is a reasonable draft, but descriptions should be checked,
and any suggestions for reorganization, highlighting, etc. are welcome.
There are no links to "getting started" pages, or work flow pages, etc.
> Programs rst

- models/wrf_hydro/python/experiment/requirements.txt
Update versions in wrf hydro py requirements. 
Note, the latest version (master branch) does not have this list of requirements.
> Update  wrf hydro py  requirements.txt to address vulnerabilities 

- CHANGELOG.rst
- conf.py
> updating to finish PR 189

- CHANGELOG.rst
- conf.py
- models/POP/readme.rst
Fixes typos in POP readme.rst.
Fixes Issue #234.
None.
> Fix typos in POP readme.rst

- CHANGELOG.rst
- assimilation_code/programs/obs_total_error/work/input.nml
- build_templates/mkmf.template.intel.osx
- build_templates/mkmf.template.pgi.linux
- build_templates/mkmf.template.pgi.osx
- conf.py
- models/model_mod_tools/work/path_names_test_quad_irreg_interp
- models/model_mod_tools/work/path_names_test_quad_reg_interp
mkmf.template changes:
* Added flags for PGI to compile 
* Removed flags causing intel not to compile (debug options) and removed vec-report flag which is no longer used.
path_names changes:
* added options_mod.f90 to path_names that were missing it (test_quad_*_interp)
input.nml changes:
* corrected typo in input.nml for obs_total_error that was causing fail in preprocess.
https://github.com/NCAR/DART/issues/219
Ran quickbuilds.
> Build fixes

- CHANGELOG.rst
- conf.py
Changelog and conf.py update for local_pf pull request
> Changelog for local pf

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- CHANGELOG.rst
- assimilation_code/programs/obs_sequence_tool/obs_sequence_tool.rst
- conf.py
fix grammar and typo in the 'Describe your preferred solution' line.
* updated feature_request.md template
* fixed markdown error in bug template
* added missing FO documentation to fix #239 
* updated changelog and conf.py version bump to 9.11.6
used a dictionary
> Fix grammar/typo in feature_request.md template and FO docs

- CHANGELOG.rst
- conf.py
- models/wrf_hydro/matlab/HydroDARTdiags.m
- models/wrf_hydro/matlab/plot_connections.m
- models/wrf_hydro/matlab/run_HydroDARTdiags.m
Improved DART diagnostic routines for wrf_hydro 
NA
I ran this new diagnostic functionality on a number of hydroDART cases on my glade/scratch
> New and Improved diagnostic routines for wrf_hydro

- CHANGELOG.rst
- assimilation_code/modules/assimilation/adaptive_inflate_mod.f90
- assimilation_code/modules/assimilation/assim_tools_mod.f90
- conf.py
Refactoring filter assim:
* Each process calculates increments vs. previously only one process would do this for each observation.  So more elements in the broadcast/send receive, and redundant (but simultaneous) calculation by each process. This is to allow future implementation of new assimilation algorithms
Code readability changes:
* removed timing variables
* get_close caching moved inside subroutine
* adaptive localization moved into subroutine
* cov_factor and adjust obs impact moved into subroutine
* Call new subroutines in adaptive_inflate_mod:
update_single_state_space_inflation, update_varying_state_space_inflation
This pull request does not (and will not) include changes to assim_tools.pf.f90, the particle filter version of assim_tools.
The timing calls for MPLOOP, LG_GRN, …
> Filter assim refactor

- README.rst
README.rst refers to 9.X.X, removing this since the release is now 10.X.X
> remove version number from README.rst

- CHANGELOG.rst
- conf.py
- models/ROMS/model_mod.f90
- models/ROMS/readme.rst
Please provide a summary of the change and include any relevant motivation and context. 
#398 
Used the WC12 dataset available for ROMS on webpub to ensure the contributed code works as described. These tests can be replicated by any reviewer.
```
cd DART/models/ROMS/work
wget https://www.image.ucar.edu/pub/DART/ROMS/dart_roms_test_data.tar.gz
tar -xzvf dart_roms_test_data.tar.gz
ln -s wc12/roms_posterior_0001_37700.nc roms_input.nc
./quickbuild.csh
./perturb_single_instance
ls -lart wc12
[ ... ]
-rw-r--r-- 1 johnsonb ncar  92398916 Sep 19 20:46 roms_posterior_0005_37700.nc
-rw-r--r-- 1 johnsonb ncar  92398916 Sep 19 20:46 roms_posterior_0006_37700.nc
-rw-r--r-- 1 johnsonb ncar  92398916 Sep 19 20:46 roms_posterior_0007_37700.nc
[ ... ]
```
> Add pert_model_copies subroutine to ROMS model_mod

- assimilation_code/modules/io/state_structure_mod.f90
While running ./model_mod_check with any model and with verbose=.true. set in input.nml, model_mod_check would segfault while in the state_structure_info() subroutine in state_structure_mod.f90 and error out during TEST 1. This was due to the write statement on line 1851 attempting to use the previously defined format 200. 
However, format 200 is actually correlated to the write statement on line 1807 and was therefore incorrectly formatted for the write on line 1851.
To fix this, I've added an additional format statement (202) that correctly formats the write that was causing the segfault. 
Fixes #390 
To test, you can use any model, but either WRF or a lorenz model will be the easiest. Make sure `verbose = .true.` in the &model_mod_check section of input.nml. Then build and run …
> bug-fix: adding another format statement in the state_structure_info() subroutine to fix segfault in model_mod_check

- models/lorenz_96_tracer_advection/work/quickbuild.sh
Set correct model for lorenz_96_tracer_advection quickbuild
fixes #420
compile and look for lorenz_96_tracer_advection/model_mod.f90 being compiled
> bug-fix: set correct model for lorenz_96_tracer_advection quickbuild

- CHANGELOG.rst
- assimilation_code/modules/utilities/clean_nml.c
- conf.py
Additional features added by @nancycollins 
Split from https://github.com/NCAR/DART/pull/422
> update to the clean_nml.c program 

- models/clm/tutorial/README.rst
Documentation changes for CLM5 tutorial based upon CLM-DART user interactions during last 1-2 months.
Resolves  #434 
Built and viewed the .rst file and made sure it rendered correctly.
> Clm5 Tutorial Documentation

- .readthedocs.yaml
yaml file for readthedocs
Fixes #471
Build docs on pull request.
> chore: add yaml for readthedocs 

- models/MOM6/model_mod.f90
Following Fortran standard to compare logicals with .eqv.
fixes #592
compiled with gfortran 12.2, 10
> mom6 model_mod .eqv. for logicals comparison

- guide/qceff-examples.rst
- guide/qceff_probit.rst
- index.rst
Documentation 
Reconciles comments made on the quantile methods pull request, which is PR five-eighty-eight #588. I'm avoiding referencing that PR with an Arabic numeral because I don't want the approval of this pull request to interfere with that one. However, merging this pull request should resolve the comments I made on five-eighty-eight.
Ran make html using Sphinx to test each of the changes to the documentation.
Worked through the four examples in `guide/qceff-examples.rst` and plotted their output with `diagnostics/matlab/plot_ens_time_series.m`
> BKJ quantile methods edit

- models/clm/shell_scripts/cesm2_2/DART_params.csh
Path correction for CLM5-DART SourceMod 
Fixes issue #622 
> Correct CLM-DART sourcemod path

- .github/workflows/action_on_pull_request.yml
GitHub is deprecation Node.js 16 actions, this pull request updates the checkout action to v4
fixes #630
Testing with a pull request to the rttov-clouds branch.
> bump github checkout action to v4

- CITATION.cff
Add a citation.cff file to help users correctly cite DART software. Creates a link to cite the repository on the landing page sidebar.
fixes https://github.com/NCAR/DART/issues/643
Followed citation file formatting on [Github Docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files)
> Create citation.cff for DART

- CITATION.cff
- README.md
- index.rst
A couple of "citing dart" info where NCAR needs changing to NSF NCAR
#584 
Todo:
* Check the citation file works
* check readme.md looks ok.
> citation change NCAR to NSF NCAR

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/documentation_issue.md
- .github/ISSUE_TEMPLATE/feature_request.md
An issue template for documentation problems. 
Also fixes a typo in the bug report template so the issue gets the label 'bug'
fixes #693 
Made an issue on my fork for docs: https://github.com/hkershaw-brown/DART/issues/5
Made an issue on my fork for a bug: https://github.com/hkershaw-brown/DART/issues/6 (bug label)
> Github template for reporting a documentation issue

- CHANGELOG.rst
- conf.py
- guide/Manhattan_diffs_from_Lanai.rst
- guide/filters.rst
- guide/important-capabilities-dart.rst
- guide/qceff-examples.rst
- guide/qceff_probit.rst
- index.rst
- models/clm/tutorial/README.rst
- models/cm1/readme.rst
Removes out-of-date reference to quantile-methods branch
Removes references to non-existant netcdf_inflation_files.rst (removed in #698) 
fixes #710 
Documentation build
> Doc fix qceff-examples & netcdf inflation files

- .github/workflows/lint_for_svn.yml
- guide/adding-your-observations-to-dart.rst
- guide/benefits-of-using-dart.rst
- guide/contributors-guide.rst
- guide/dart-design-philosophy.rst
- guide/important-capabilities-dart.rst
- index.rst
Fixes the links in the "benefits of using dart" page
Added anchors to linked sections that did not already have them
Fixed typos in guide/contributors-guide.rst
fixes #829
Local documentation build. Clicky-click the links.
> doc-fix: fix links in benefits of using dart

- observations/obs_converters/CONAGUA/README.rst
Removed irrelevant information about MODIS and
other converters and added converter-specific
details.
Cleaned up the readme of the conagua convertor. Removed irrelevant information and added useful details about the converter
Partial fix to issue #864 
Fixes #868 
No tests
> Updated CONAGUA readme

- CHANGELOG.rst
- conf.py
- observations/forward_operators/obs_def_cice_mod.f90
Please provide a summary of the change and include any relevant motivation and context. 
Part of CICE improvements from #841
Fixes #843
None yet.
> Freeboard fwd operator for radar, laser

- models/clm/tutorial/README.rst
Updating CLM (CESM) porting instruction link, reported by user.
#938 
N/A:  Simple documentation link update in documentation.
- [ X] Documentation updated
> CLM porting link update
